### ISSUE TITLE
你好  请问一下怎么设置不回调fetchMoreData

### ISSUE THREAD

**Issue by ghost** [472647301/react-native-byron-kline#5]

**Comment by ghost** [comment]
因为我的数据是一个接口全部获取的      当我滑动的时候 volume 后边就会出现loading 然后屏幕会出现一个蒙版  会卡很长时间

**Comment by 472647301** [comment]
已经移除蒙版了，无法设置不回调，但是你可以在fetchMoreData回调传入一个空数组，这样就会通知图表无更多数据了
